# Generated by Django 4.0.4 on 2022-09-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='media/')),
                ('name', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
            ],
        ),
    ]
